### ISSUE TITLE
Alternate Solution to Changing Dockerfile , building Image and Running Image Everytime a new dependency is needed

### ISSUE THREAD

**Issue by AditModi** [rubiin/jenkins#3]
I am using your custom Dockerfile which includes jenkins image and additionally I also need additional dependencies like docker , node etc pre-installed which I am able to configure in Dockerfile .

Now,
If in the future I would need to make any changes in the Dockerfile because I need to install another dependency like nginx to be installed then I change Dockerfile , build the image and use it again , seems like too much to do , everytime I need a new dependency .

Any alternative solution available to resolve this hassle.

**Comment by rubiin** [comment]
You can try to connect to the container shell and install any dependencies without having to rebuild the running container. Hope it helps
